---
    - name: Yum update packages
      yum:
        name: '*'
        state: latest
        skip_broken: yes
        exclude: mysql*

    - name: yum_install_packages
      yum: name={{ item }} state=latest
      with_items:
        - vim
        - wget
        - tree
        - libselinux-python
        - git
        - yum-utils
      when: yum_install == "Y"
